version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    container_name: codex-backend

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    container_name: codex-frontend
